// <auto-generated />
namespace MyAttendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class a123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a123));
        
        string IMigrationMetadata.Id
        {
            get { return "202107161449444_a123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
