// <auto-generated />
namespace MyAttendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class a234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a234));
        
        string IMigrationMetadata.Id
        {
            get { return "202107310642218_a234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
