// <auto-generated />
namespace MyAttendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remaining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remaining));
        
        string IMigrationMetadata.Id
        {
            get { return "202108080708347_remaining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
