// <auto-generated />
namespace MyAttendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class User_and_userType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_and_userType));
        
        string IMigrationMetadata.Id
        {
            get { return "202107110606282_User_and_userType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
